### PR TITLE
fix(warnings): Check if linter-eslint is actually active instead of reading user config

### LINKED ISSUE #168: Warning about linter-eslint fix on save (coming from prettier-atom) when linter-eslint is not installed
I keep getting a warning telling me that linter-eslint's fix on save feature is enabled (warning is coming from prettier-atom). But I don't even have the linter-eslint package installed in my editor...nothing obvious coming up other than the following from prettier:debug (and a line telling me that this issue has already been reported):

`Error: ENOENT: no such file or directory, open 'package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at Function.module.exports.sync.fp [as sync] (/home/cheyenne/.atom/packages/prettier-atom/node_modules/load-json-file/index.js:11:38)
    at Function.module.exports.sync (/home/cheyenne/.atom/packages/prettier-atom/node_modules/read-pkg/index.js:40:25)
    at getDebugInfo (/home/cheyenne/.atom/packages/prettier-atom/dist/displayDebugInfo/index.js:16:89)
    at displayDebugInfo (/home/cheyenne/.atom/packages/prettier-atom/dist/displayDebugInfo/index.js:21:13)
    at atom-workspace.lazyDisplayDebugInfo (/home/cheyenne/.atom/packages/prettier-atom/dist/main.js:58:3)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)`

### PR DESCRIPTION
**Pull request by darahak**
Fixes #168

### CODE REVIEW

File: src/warnAboutLinterEslintFixOnSave/index.js [hunk 1]
```diff
@@ -1,14 +1,21 @@
...
   'We recommend disabling this feature when using the ESlint integration from prettier-atom';
 const OPTIONS = { dismissable: true };
 
+const isLinterEslintActive = () => isPackageActive('linter-eslint');
+
 const displayWarning = () => addWarningNotification(MESSAGE, OPTIONS);
 
 const warnAboutLinterEslintFixOnSave = () =>
-  shouldUseEslint() && isLinterEslintAutofixEnabled() && displayWarning();
+  isLinterEslintActive() && shouldUseEslint() && isLinterEslintAutofixEnabled() && displayWarning();
```
Comment (robwise) [inline src/warnAboutLinterEslintFixOnSave/index.js]: let's keep the API simpler by having `atomInterface` just expose `isLinterEslintEslintAutofixEnabled`. This way we don't have to do more than one thing in this function. In addition, we will simply be able to mock out `isLinterEslintAutofixEnabled`, instead of having to mock the atom interface outside of the atomInterface tests.

Comment (darahak) [inline src/warnAboutLinterEslintFixOnSave/index.js]: Done!
